---
name: Build Tag

on:  # yamllint disable-line
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@fc57041b2a1f991b8d8dcf7ed4a7bd03a56bc4e3 # 1.7.0
    with:
      tag: ${{ github.ref_name }}
      repo: freezing-sync
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
