---
name: Build and Deploy Latest

on:  # yamllint disable-line
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:

  build:
    permissions:
      contents: read
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@188155b3d3466278116cafb2a3b3c1c2c4773613 # harden-workflows, pending 1.7.0
    concurrency: build-deploy-and-test
    with:
      tag: latest
      repo: freezing-sync
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    permissions:
      contents: read
    environment: production
    concurrency: build-deploy-and-test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: install
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          set -euo pipefail
          cd /opt/compose
          docker compose pull freezing-sync
          docker compose up -d freezing-sync
