---
name: Build

on: pull_request  # yamllint disable-line

jobs:
  build:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.4.18
    with:
      tag: latest-actions-build
      repo: freezing-sync
    secrets: inherit
